# Generated by Django 4.2.13 on 2024-07-30 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_booking_total_days_alter_booking_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='gst',
            field=models.IntegerField(default=5, verbose_name='GST %'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 12, 29, 29, 137671)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 12, 29, 29, 137691)),
        ),
    ]
