# Generated by Django 4.2.14 on 2024-07-23 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_booking_check_out_alter_booking_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
